import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :api_uploader, ApiUploaderWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: ApiUploader.Finch

# Do not print debug messages in production
config :logger, level: :info

config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  region: System.get_env("AWS_REGION") || "us-east-2"

# debug_requests: true

config :ex_aws, :s3,
  scheme: "https://",
  host: "s3-us-east-2.amazonaws.com",
  bucket: "themeforest-vault",
  region: "us-east-2"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
